name: Binary Compatibility

on:
  pull_request:
  push:
    branches:
      - master
      - main
    tags:
      - v2.6.*

permissions: {}

jobs:
  check-binary-compatibility:
    name: Check / Binary Compatibility
    runs-on: ubuntu-20.04
    if: github.repository == 'apache/incubator-pekko'
    strategy:
      fail-fast: false
      matrix:
        # The versions of scala specified here are only used as `+~...`
        # which ignores the PATCH portion of the version id. These Scala versions don't need
        # to be fully defined here then since Pekko build handles which patch version will be used.
        scalaVersion: [ "2.12", "2.13" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: Enable jvm-opts
        run: cp .jvmopts-ci .jvmopts

      - name: Compile code
        run: sbt "+~ ${{ matrix.scalaVersion }} Test/compile"

      - name: Report MiMa Binary Issues
        run: |-
          sbt "+~ ${{ matrix.scalaVersion }} mimaReportBinaryIssues"

      - name: Check correct MiMa filter directories
        run: |
          sbt checkMimaFilterDirectories
