name: Binary Compatibility

on:
  pull_request:
  push:
    branches:
      - master
      - main
    tags:
      - v2.6.*

jobs:
  check-binary-compatibility:
    name: Check / Binary Compatibility
    runs-on: ubuntu-20.04
    if: github.repository == 'apache/incubator-pekko'
    strategy:
      fail-fast: false
      matrix:
        # The versions of scala specified here are only used as `+~...`
        # which ignores the PATCH portion of the version id. These Scala versions don't need
        # to be fully defined here then since Akka build handles which patch version will be used.
        scalaVersion: [ "2.12", "2.13" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Set up JDK 8
        uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.8.0

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: Enable jvm-opts
        run: cp .jvmopts-ci .jvmopts

      # compile code instead of doing mima check (until we re-enable mima check)
      - name: Compile code
        run: sbt "+~ ${{ matrix.scalaVersion }} Test/compile"

      # disable mima check until first pekko release is done
      #- name: Report MiMa Binary Issues
      #  run: sbt "+~ ${{ matrix.scalaVersion }} mimaReportBinaryIssues"

      #- name: Check correct MiMa filter directories
      #  run: sbt checkMimaFilterDirectories

      # comment out email actions until we have an email address to use (and we need to get INFRA to whitelist dawidd6/action-send-mail)
      #- name: Email on failure
      #  if: ${{ failure() }}
      #  uses: dawidd6/action-send-mail@v3
      #  with:
      #    server_address: smtp.gmail.com
      #    server_port: 465
      #    username: ${{secrets.MAIL_USERNAME}}
      #    password: ${{secrets.MAIL_PASSWORD}}
      #    subject: "Failed: ${{ github.workflow }} / ${{ github.job }}"
      #    to: akka.official@gmail.com
      #    from: Akka CI (GHActions)
      #    body: |
      #      Job ${{ github.job }} in workflow ${{ github.workflow }} of ${{github.repository}} failed!
      #      https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
