name: Nightly Builds (Windows)

on:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  win-test:
    name: Pekko Tests
    runs-on: windows-latest
    if: github.repository == 'apache/incubator-pekko'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: Enable jvm-opts
        run: copy .jvmopts-ci .jvmopts

      - name: sbt test
        run: |-
          sbt test