name: Timing sensitive tests

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {}

jobs:

  pekko-timing-sensitive-tests:
    name: Pekko Tests taggedAs TimingTest
    runs-on: ubuntu-20.04
    if: github.repository == 'apache/incubator-pekko'
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: Enable jvm-opts
        run: cp .jvmopts-ci .jvmopts

      - name: sbt test
        run: |-
          sbt \
            -Djava.security.egd=file:/dev/./urandom \
            -Dpekko.cluster.assert=on \
            -Dpekko.test.timefactor=2 \
            -Dpekko.actor.testkit.typed.timefactor=2 \
            -Dpekko.test.tags.only=timing \
            -Dpekko.log.timestamps=true \
            -Dpekko.test.multi-in-test=false \
            -Dmultinode.XX:MetaspaceSize=128M \
            -Dmultinode.Xms256M \
            -Dmultinode.Xmx256M \
            -Dmultinode.XX:+AlwaysActAsServerClassMachine \
            clean test

      - name: Test Reports
        # Makes it easier to spot failures instead of looking at the logs.
        if: ${{ failure() }}
        uses: marcospereira/action-surefire-report@v1
        with:
          report_paths: '**/target/test-reports/TEST-*.xml'
          fail_if_no_tests: false
          skip_publishing: true

      # comment out email actions until we have an email address to use (and we need to get INFRA to whitelist dawidd6/action-send-mail)
      #- name: Email on failure
      #  if: ${{ failure() }}
      #  uses: dawidd6/action-send-mail@v3
      #  with:
      #    server_address: smtp.gmail.com
      #    server_port: 465
      #    username: ${{secrets.MAIL_USERNAME}}
      #    password: ${{secrets.MAIL_PASSWORD}}
      #    subject: "Failed: ${{ github.workflow }} / ${{ github.job }}"
      #    to: akka.official@gmail.com
      #    from: Akka CI (GHActions)
      #    body: |
      #      Job ${{ github.job }} in workflow ${{ github.workflow }} of ${{github.repository}} failed!
      #      https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
